//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.25 at 05:03:18 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://data.altinkaynak.com/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dev.turkdogan.currencyrate.source.altinkaynak.ws;
